name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "avr/libraries/**"
      - "avr/cores/**"
      - "avr/variants/**"
      - "avr/*.txt"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "avr/libraries/**"
      - "avr/cores/**"
      - "avr/variants/**"
      - "avr/*.txt"
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    env:
      platform-name: ATTinyCore:avr

      available-flash-8kB-plus-true-sketch-paths: |
        - avr/libraries/SPI/examples/BarometricPressureSensor
        - avr/libraries/SoftwareSerial/examples/TwoPortReceive
        - avr/libraries/Wire/examples/SFRRanger_reader
        - avr/libraries/tinyNeoPixel/examples/RGBWstrandtest
      available-flash-4kB-plus-true-sketch-paths: |
        - avr/libraries/EEPROM/examples/eeprom_crc
        - avr/libraries/EEPROM/examples/eeprom_put
        - avr/libraries/EEPROM/examples/eeprom_read
        - avr/libraries/Wire/examples/digital_potentiometer
        - avr/libraries/SoftwareSerial/examples/SoftwareSerialExample
        - avr/libraries/tinyNeoPixel/examples/buttoncycler
        - avr/libraries/tinyNeoPixel/examples/simple
        - avr/libraries/tinyNeoPixel/examples/strandtest
        - avr/libraries/tinyNeoPixel_Static/examples/buttoncycler
        - avr/libraries/tinyNeoPixel_Static/examples/strandtest
      available-flash-2kB-plus-true-sketch-paths: |
        - avr/extras/ci/test_sketches_2k/basic_test

    strategy:
      fail-fast: false

      matrix:
        device:
          #- attinyx4:chip=84
          #- attinyx4:chip=44
          #- attinyx4:chip=24
          #- attinyx41:chip=841
          #- attinyx41:chip=441
          - attinyx5:chip=85
          #- attinyx5:chip=45
          #- attinyx5:chip=25
          #- attinyx61:chip=861
          #- attinyx61:chip=461
          #- attinyx61:chip=261
          #- attinyx7:chip=167
          #- attinyx7:chip=87
          #- attinyx8:chip=88
          #- attinyx8:chip=48
          - attiny1634
          #- attinyx313:chip=4313
          #- attinyx313:chip=2313a
          #- attiny828
          #- attiny43u
          #- attiny26
        softserial:
          -
          - enable
          - txonly

        # Filter out these matrix combinations
        exclude:
          #- softserial: enable
          #  device: attinyx41:chip=841
          #- softserial: enable
          #  device: attinyx41:chip=441
          #- softserial: txonly
          #  device: attinyx41:chip=841
          #- softserial: txonly
          #  device: attinyx41:chip=441
          #- softserial: enable
          #  device: attinyx7:chip=87
          #- softserial: enable
          #  device: attinyx7:chip=167
          #- softserial: txonly
          #  device: attinyx7:chip=87
          #- softserial: txonly
          #  device: attinyx7:chip=167
          #- softserial: enable
          #  device: attinyx313:chip=4313
          #- softserial: enable
          #  device: attinyx313:chip=2313a
          #- softserial: txonly
          #  device: attinyx313:chip=4313
          #- softserial: txonly
          #  device: attinyx313:chip=2313a
          - softserial: enable
            device: attiny1634
          - softserial: txonly
            device: attiny1634
          #- softserial: txonly
          #  device: attiny828
          #- softserial: txonly
          #  device: attiny828
          #- softserial:
          #  device: attinyx4:chip=84
          #- softserial:
          #  device: attinyx4:chip=44
          #- softserial:
          #  device: attinyx4:chip=24
          - softserial:
            device: attinyx5:chip=85
          #- softserial:
          #  device: attinyx5:chip=45
          #- softserial:
          #  device: attinyx5:chip=25
          #- softserial:
          #  device: attinyx61:chip=861
          #- softserial:
          #  device: attinyx61:chip=461
          #- softserial:
          #  device: attinyx61:chip=261
          #- softserial:
          #  device: attinyx8:chip=88
          #- softserial:
          #  device: attinyx8:chip=48
          #- softserial:
          #  device: attiny43u
          #- softserial:
          #  device: attiny26
        include:
          - device: attiny1634
            available-flash-kB: 16
          #- device: attinyx7:chip=167
          #  available-flash-kB: 16
          #- device: attinyx7:chip=87
          #  available-flash-kB: 8
          #- device: attinyx4:chip=84
          #  available-flash-kB: 8
          #- device: attinyx4:chip=44
          #  available-flash-kB: 4
          #- device: attinyx4:chip=24
          #  available-flash-kB: 2
          #- device: attinyx41:chip=841
          #  available-flash-kB: 8
          #- device: attinyx41:chip=441
          #  available-flash-kB: 4
          - device: attinyx5:chip=85
            available-flash-kB: 5
          #- device: attinyx5:chip=45
          #  available-flash-kB: 4
          #- device: attinyx5:chip=25
          #  available-flash-kB: 2
          #- device: attinyx61:chip=861
          #  available-flash-kB: 8
          #- device: attinyx61:chip=461
          #  available-flash-kB: 4
          #- device: attinyx61:chip=261
          #  available-flash-kB: 2
          #- device: attinyx8:chip=88
          #  available-flash-kB: 8
          #- device: attinyx8:chip=48
          #  available-flash-kB: 4
          #- device: attinyx313:chip=4313
          #  available-flash-kB: 4
          #- device: attinyx313:chip=2313a
          #  available-flash-kB: 2
          #- device: attiny828
          #  available-flash-kB: 8
          #- device: attiny43u
          #  available-flash-kB: 4
          #- device: attiny26
          #  available-flash-kB: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches/README.md
      - name: Compile examples (all default)
        uses: arduino/compile-sketches@main
        env:
          FIRST_DELIM: ${{contains(matrix.device, ':') && ',' || ':'}}
          SOFT_SERIAL_PREFIX: ${{matrix.softserial != '' && ',softserial=' || ''}}
        with:
          fqbn: ${{env.platform-name}}:${{matrix.device}}${{env.FIRST_DELIM}}clock=internal_8m${{env.SOFT_SERIAL_PREFIX}}${{matrix.softserial}}
          sketch-paths: |
            # It's necessary to jump through some hoops to dynamically generate the env object keys to define the non-universal sketch paths
            # https://docs.github.com/en/actions/learn-github-actions/expressions#format
            ${{ env[format('available-flash-8kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 7.5)] }}
            ${{ env[format('available-flash-4kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 4)] }}
            ${{ env[format('available-flash-2kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 2)] }}
          platforms: |
            # Install ATTinyCore via Boards Manager for the toolchain
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ${{ env.platform-name }}
            # Overwrite the ATTinyCore release version with the platform from the local path
            - source-path: avr
              name: ${{ env.platform-name }}
          libraries: |
            # The sketches don't have any external library dependencies, so just define an empty array
            -
          verbose: false
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: sketches-reports
